### ISSUE TITLE
keybase account?

### ISSUE THREAD

**Issue by sylph01** [hashedhyphen/hashedhyphen.com#3]
https://keybase.io/hashedhyphen

**Comment by hashedhyphen** [comment]
Nice catch!

**Comment by hashedhyphen** [comment]
Successfully deployed. Thanks 🍵 

<img width="395" alt="image" src="https://user-images.githubusercontent.com/13907611/49927379-1bb99f00-ff01-11e8-84e6-4d01f1fbe1df.png">

**Comment by sylph01** [comment]
🎉
